// fabrica/frontend/src/views/AjustesTienda.vue
<script setup>
import { ref } from 'vue'
import { useAuth } from '../composables/useAuth'
import { useStoreInfo } from '../composables/useStoreInfo'
import { useToast } from '../composables/useToast'

const { isAdmin } = useAuth()
const { storeInfo, updateStoreInfo, resetStoreInfo } = useStoreInfo()
const { success } = useToast()

const form = ref({
  name: storeInfo.value.name,
  subtitle: storeInfo.value.subtitle,
  generalInfo: storeInfo.value.generalInfo,
})

function save() {
  updateStoreInfo(form.value)
  success('Encabezado actualizado')
}

function restoreDefaults() {
  resetStoreInfo()
  form.value = {
    name: 'Fabrica',
    subtitle: 'Agencias Vehiculos',
    generalInfo: 'Catalogo principal',
  }
  success('Valores por defecto restaurados')
}
</script>

<template>
  <div class="ajustes-page">
    <h1>Ajustes de tienda</h1>
    <p class="sub">Edita nombre y texto general del encabezado lateral.</p>

    <div v-if="!isAdmin" class="warn">Solo administradores pueden editar estos ajustes.</div>

    <form v-else class="form-grid" @submit.prevent="save">
      <div class="form-group">
        <label>Nombre de tienda</label>
        <input v-model="form.name" placeholder="Fabrica Central" />
      </div>
      <div class="form-group">
        <label>Subtitulo</label>
        <input v-model="form.subtitle" placeholder="Agencias Vehiculos" />
      </div>
      <div class="form-group">
        <label>Informacion general</label>
        <input v-model="form.generalInfo" placeholder="Repuestos multimarca" />
      </div>
      <div class="actions">
        <button class="btn btn-primary" type="submit">Guardar</button>
        <button class="btn btn-secondary" type="button" @click="restoreDefaults">Restaurar por defecto</button>
      </div>
    </form>
  </div>
</template>

<style scoped>
.ajustes-page { max-width: 900px; }
.sub { color: #64748b; margin-top: 0; }
.warn { padding: .75rem 1rem; border: 1px solid #fecaca; background: #fff1f2; color: #9f1239; border-radius: 8px; }
.form-grid { display: grid; gap: 1rem; margin-top: 1rem; }
.form-group label { display: block; font-weight: 600; margin-bottom: .4rem; }
.form-group input { width: 100%; padding: .55rem .7rem; border-radius: 8px; border: 1px solid #cbd5e1; }
.actions { display: flex; gap: .75rem; }
</style>

// distribuidores/frontend/src/views/AjustesTienda.tsx
import { useState } from 'react'
import { Link } from 'react-router-dom'
import { useAuth } from '../context/AuthContext'
import { useStoreInfo } from '../context/StoreInfoContext'
import { useToast } from '../context/ToastContext'

export function AjustesTienda() {
  const { user, isLoggedIn } = useAuth()
  const { info, update, reset } = useStoreInfo()
  const toast = useToast()
  const isAdmin = isLoggedIn && user?.roles?.includes('ADMIN')

  const [name, setName] = useState(info.name)
  const [subtitle, setSubtitle] = useState(info.subtitle)
  const [generalInfo, setGeneralInfo] = useState(info.generalInfo)

  if (!isAdmin) {
    return (
      <div className="productos-admin">
        <h1>Ajustes de tienda</h1>
        <p>Solo administradores pueden editar el encabezado de la tienda.</p>
        <Link to="/">Volver al inicio</Link>
      </div>
    )
  }

  return (
    <div className="productos-admin">
      <header className="page-header">
        <h1>Ajustes del encabezado</h1>
        <p className="page-subtitle">Personaliza nombre de tienda e informacion general visible en la barra lateral.</p>
      </header>
      <form
        className="producto-form-fields"
        onSubmit={(e) => {
          e.preventDefault()
          update({ name, subtitle, generalInfo })
          toast.success('Encabezado actualizado')
        }}
      >
        <div className="form-group">
          <label>Nombre de tienda</label>
          <input value={name} onChange={(e) => setName(e.target.value)} placeholder="Distribuidora Centro" />
        </div>
        <div className="form-group">
          <label>Subtitulo</label>
          <input value={subtitle} onChange={(e) => setSubtitle(e.target.value)} placeholder="Agencias Vehiculos" />
        </div>
        <div className="form-group">
          <label>Informacion general</label>
          <input value={generalInfo} onChange={(e) => setGeneralInfo(e.target.value)} placeholder="Repuestos multimarca" />
        </div>
        <div className="form-actions">
          <button className="btn btn-primary" type="submit">
            Guardar
          </button>
          <button
            className="btn btn-secondary"
            type="button"
            onClick={() => {
              reset()
              setName('Distribuidora')
              setSubtitle('Agencias Vehiculos')
              setGeneralInfo('Repuestos multiorigen')
              toast.success('Valores restaurados')
            }}
          >
            Restaurar por defecto
          </button>
        </div>
      </form>
    </div>
  )
}
